# -*- coding: utf-8 -*-
"""chatbot NLP BERT.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10CbghCa8w4_OBfeZDYbsYId07id6869n
"""



"""!pip install transformers
!pip install datasets
!pip install accelerate
!pip install torch
!pip uninstall -y googletrans httpx httpcore
!pip install googletrans-py"""


import os
os.system("pip install sentencepiece")

import pandas as pd
import torch
from transformers import AutoTokenizer, AutoModelForSequenceClassification, pipeline
from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware


df = pd.read_excel("merged_chatbot_dataset.xlsx")  
df["text"] = df["example"].astype(str)
df["label"] = df["intent"].astype("category").cat.codes
label2intent = dict(enumerate(df["intent"].astype("category").cat.categories))



model_name = "distilbert-base-multilingual-cased"
tokenizer = AutoTokenizer.from_pretrained(model_name)
model = AutoModelForSequenceClassification.from_pretrained(
    model_name, num_labels=len(df["label"].unique())
)
model.eval()

def predict_intent(text):
    inputs = tokenizer(text, return_tensors="pt", padding=True, truncation=True)
    with torch.no_grad():
        outputs = model(**inputs)
    pred = torch.argmax(outputs.logits, dim=1).item()
    return label2intent[pred]



translator = pipeline("translation", model="Helsinki-NLP/opus-mt-en-ar")

def detect_language(text):
    for ch in text:
        if '\u0600' <= ch <= '\u06FF':
            return "ar"
    return "en"

def bot_reply(message):
    user_lang = detect_language(message)
    intent = predict_intent(message)
    row = df[df["intent"] == intent].iloc[0]

    response_text = None

    if user_lang == "ar":
        if row["language"] == "ar":
            response_text = row["response"]
        else:
            try:
                response_text = translator(row["response"])[0]["translation_text"]
            except:
                response_text = "حدثت مشكلة في الترجمة"
    else:  # English question
        if row["language"] == "en":
            response_text = row["response"]
        else:
            response_text = row["response"]   

    return {
        "language": user_lang,
        "response": response_text
    }




app = FastAPI(title="Arabic-English BERT Chatbot")


app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

@app.post("/chat")
def chat(message: str):
    return bot_reply(message)


if __name__ == "__main__":
    import uvicorn
    print(bot_reply("أفضل غسالة"))
    uvicorn.run(app, host="0.0.0.0", port=7860)
